language: php

# php compatibility
php: ["7.3", "7.4", "nightly"]

matrix:
  allow_failures:
    - php: "nightly"

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --verbose --dry-run
  - vendor/bin/phpcs --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan analyse --no-progress --verbose --level max src/ tests/

notifications:
  email:
    if: branch = master
